networks:
  backend:
    driver: bridge

services:
  app:
    build: '.'
    env_file:
      - ".env"
    volumes:
      - .:/app
    ports:
      - 8080:8080
    depends_on:
      - postgres
      - redis
    networks:
      - backend

  postgres:
    image: 'postgres:12-alpine'
    expose:
      - 5432
    ports:
      - 5432:5432
    networks:
      - backend
    env_file:
      - ".env"

  redis:
    image: 'redis:alpine3.17'
    expose:
      - 6379
    ports:
      - 6379:6379
    networks:
      - backend
    env_file:
      - ".env"
    command: redis-server --requirepass ${REDIS_PASS}